#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell such as ksh or
#       bash, then change the shebang line to use that shell, and "re-execute"
#       the script. More details at http://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
#
#   (2) The slurping of gradle.properties into local variables can cause problems
#       when there are spaces in those values. Take care (know how to set jvm
#       args) and test this script before using it in an automated context.
#
#   Typical usage is as follows:
#
#        #!/bin/bash
#        cd $(dirname "$0")
#        ./gradlew <some task>
#
#   or to specify the Java home directory:
#
#        #!/bin/bash
#        export JAVA_HOME=/path/to/java
#        cd $(dirname "$0")
#        ./gradlew <some task>
#
#   or on Windows with the Batch file:
#
#        cmd /c gradlew <some task>
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    PRG=`readlink "$PRG"`
done
SAVED="`pwd`"
cd "`dirname "$PRG"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != maximum.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`

    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 3 -type d -name gradle 2>/dev/null`
    SEP=""
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS="$ROOTDIRS$SEP$dir"
        SEP="|"
    done
    OURCYGPATTERN="(^($ROOTDIRS)$)"
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGWIN_VERBOSE" = "true" ] ; then
        echo "ROOTDIRS=$ROOTDIRS"
        echo "OURCYGPATTERN=$OURCYGPATTERN"
        echo "CLASSPATH=$CLASSPATH"
        echo "JAVACMD=$JAVACMD"
        echo
    fi
    # Split up the JVM_OPTS And GRADLE_OPTS values into an array, following the shell quoting and substitution rules
    # to make sure that they still are split up correctly
    local arguments=()
    IFS=$'\n'
    for arg in $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS ; do
        if [[ $arg =~ ^-.*\.jar$ ]] ; then
            arguments+=( "$arg" )
        else
            arguments+=( "$(cygpath --unix "$arg")" )
        fi
    done
    IFS=
    # Now convert the arguments back to Windows format (space and all) that we can pass to java
    i=0
    for arg in "${arguments[@]}" ; do
        arg=`cygpath --windows "$arg"`
        args="$args \"$arg\""
        i=$((i+1))
    done
    printf '%s\n' "$args"
else
    for arg do
        if [[ $arg =~ ^-.*\.jar$ ]] ; then
            args+=( "$arg" )
        else
            args+=( "$(printf '%s\n' "$arg" | sed -e 's/[][]/\\&/g')" )
        fi
    done
    printf '%s\n' "${args[@]}"
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell commands, so put them in double quotes to make sure that they get
#     re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, when -r it skips empty lines.
# IFS is set to newline as this is the only character that cannot occur in filenames.
# The triple backslash is an escaped backslash and IFS ends up as a newline.
#
# We use "printf %s" to avoid issues with the shell's echo builtin.
# The printf command replaces each newline with the string from IFS, which is newline,
# making each arg be on a new line as required.
#
# IFS needs to be saved before the command substitution below so that it takes precedence
# over a user defined IFS which has the last non-newline character as IFS.
# This is the "true" terminal "new line" character.
IFS="$(printf '\n')"
eval "set -- $(printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" | xargs printf '%s\n')" -- "$(printf '%s\n' "$@" | xargs printf '%s\n')"
IFS="$SAVED_IFS"
exec "$JAVACMD" "$@"
